// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "backend/components"

// Template that renders the main page of the application.
// It showcases the technologies used in the project through a series of logos,
// and includes an interactive counter component that updates upon user interaction.
func Index(counter int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h2>Technologies Used:</h2><div><div class=\"flex items-center justify-center flex-row\"><a href=\"https://go.dev/\" target=\"_blank\"><img src=\"/public/golang.svg\" class=\"size-40 logo go\" alt=\"Go logo\"></a><a href=\"https://templ.guide/\" target=\"_blank\"><img src=\"/public/templ.svg\" style=\"height: 10rem; width: 10rem;\" class=\"logo templ\" alt=\"Templ logo\"></a><a href=\"https://htmx.org/\" target=\"_blank\"><img src=\"/public/htmx.svg\" class=\"size-40 logo htmx\" alt=\"HTMX logo\"></a><a href=\"https://alpinejs.dev/\" target=\"_blank\"><img src=\"/public/alpinejs.svg\" class=\"size-40 logo alpine\" alt=\"Alpine.js logo\"></a></div><h1>Critique of the <span class=\"text-cyan-300\">Gotha</span> Program</h1><div class=\"card\"><button id=\"button\" hx-post=\"/count\" type=\"button\" hx-swap=\"innerHTML\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Count(counter).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</button></div><p class=\"read-the-docs\">Click on the button and update the page to see the magic!</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
